### ISSUE TITLE
Package for PYPI

### ISSUE THREAD

**Issue by Freed-Wu** [annacrombie/muon#160]
There are many build system are packaged to PYPI in order to build python module in C/C++

- [cmake](https://pypi.org/project/cmake/)
- [meson](https://pypi.org/project/meson/)
- [xmake](https://pypi.org/project/xmake-wheel/)
- [ninja](https://pypi.org/project/ninja/)
- [gnumake](https://pypi.org/project/gnumake/)

Maybe muon can be packaged, too.

I do a simple experiment:

Because muon can be built in meson, so

`pyproject.toml`:

```toml
[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[project]
name = 'muon'
description = 'muon is an implementation of the meson build system in c99 with minimal dependencies.'
readme = 'README.md'
dynamic = ["version"]

# [tool.meson-python.args]
# setup = ['-Dstatic=true']
```

Due to

```
meson-python: error: Could not map installation path to an equivalent wheel directory: '{mandir}/man1/muon.1'
```

Comment `doc/meson.build` temporarily:

```meson
            # install: true,
```

Now

```sh
$ uv build --wheel
$ uv pip install --prefix /tmp/muon dist/*.whl
$ tree /tmp/muon
 /tmp/muon
├──  bin
│   └──  muon
└──  lib
    └──  python3.13
        └──  site-packages
            └──  muon-0.5.0.dist-info
                ├──  direct_url.json
                ├──  INSTALLER
                ├──  METADATA
                ├──  RECORD
                ├──  REQUESTED
                └──  WHEEL
```

1. manpag document is commented
2. muon is dynamically linked to some libraries. Had better be static.
